ByteBusterApp/accounts/urls.py
# accounts/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

ByteBusterApp/urls.py
from django.urls import path
from . import views
from .views import edit_template

# from .views import LabGroupMembersView, SignUpView

app_name = 'ByteBusterApp'

urlpatterns = [
    path('load_template/<str:template_id>', views.load_template, name='load_template'),
    path('', views.homepage, name='homepage'),
    path('template1', views.temp1, name='template1'),
    path('template2', views.temp2, name='template2'),
    path('template3', views.temp3, name='template3'),
    path('template1editor', views.temp1edit, name='template1editor'),
    path('template2editor', views.temp2edit, name='template2editor'),
    path('template3editor', views.temp3edit, name='template3editor'),
    path('pricing', views.pricingpage, name='pricingpage'),
    path('paymentsuccess', views.paymentsuccess, name='paymentsuccess'),
    path('paymentfailed', views.paymentfailed, name='paymentfailed'),

    path('dashboard', views.dashboard, name='dashboard'),
    # path('login/', views.login_here, name='login'),
    # path('logout/', views.logout_here, name='logout'),
    path('template_editor/', edit_template, name='edit_template'),
]

ByteBusterProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', include('ByteBusterApp.urls', namespace='ByteBusterApp')),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('', include('paypal.standard.ipn.urls')),
]

accounts/urls.py
from django.urls import path

from .views import SignUpView, CustomLoginView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path('accounts/login/', CustomLoginView.as_view(), name='login'),
]

ByteBusterApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Model
from django.urls import reverse
from django.utils.safestring import mark_safe


class payment(models.Model):
    paymentdone = models.BooleanField(default=False)
    userid = models.ForeignKey(User, on_delete=models.CASCADE)

accounts/models.py
from django.db import models

# Create your models here.

ByteBusterApp/forms.py
# template_editor/forms.py
from django import forms

class TemplateForm(forms.Form):
    template_content = forms.CharField(widget=forms.Textarea)

ByteBusterApp/accounts/views.py
# accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"


class CustomLoginView(LoginView):
    template_name = 'registration/login.html'

ByteBusterApp/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.http import FileResponse
from paypal.standard.forms import PayPalPaymentsForm
from django.conf import settings
import  uuid
from django.urls import reverse
from django.shortcuts import render
from django.template.loader import render_to_string
from .forms import TemplateForm
from .models import payment


def edit_template(request):
    if request.method == 'POST':
        form = TemplateForm(request.POST)
        if form.is_valid():
            template_content = form.cleaned_data['template_content']
            # Render the template with the updated content
            updated_template = render_to_string('template_editor.html', {'template_content': template_content})
            embedded_code = f'<script>document.write(`{updated_template}`);</script>'
            return render(request, 'template_editor.html', {'form': form, 'embedded_code': embedded_code})
    else:
        form = TemplateForm()
    return render(request, 'template_editor.html', {'form': form})


def homepage(request):
    detail = ''
    if request.user.is_authenticated:
        detail = payment.objects.get(userid=request.user)

    return render(request, 'ByteBusterApp/homepage.html' , {'detail': detail})


def temp1(request):
    return render(request, 'ByteBusterApp/template1.html')


def temp1edit(request):
    return render(request, 'ByteBusterApp/template1editor.html')


def temp2(request):
    return render(request, 'ByteBusterApp/template2.html')


def temp2edit(request):
    return render(request, 'ByteBusterApp/template2editor.html')


def temp3(request):
    return render(request, 'ByteBusterApp/template3.html')


def temp3edit(request):
    return render(request, 'ByteBusterApp/template3editor.html')


@login_required
def pricingpage(request):
    host = request.get_host()
    paypal_checkout = {
        'business': settings.PAYPAL_RECEIVER_EMAIL,
        'amount': 10,
        'invoice': uuid.uuid4(),
        'currency_code': 'CAD',
        'notify_url': f"http://{host}:{reverse('paypal-ipn')}",
        'return_url': f"http://{host}{reverse('ByteBusterApp:paymentsuccess')}",
        'cancel_url': f"http://{host}{reverse('ByteBusterApp:paymentfailed')}",
    }

    paypal_payment = PayPalPaymentsForm(initial=paypal_checkout)

    return render(request, 'ByteBusterApp/pricingpage.html',{'paypal_payment' : paypal_payment})



@login_required
def paymentsuccess(request):
    payer_id = request.GET.get('PayerID', None)
    paymentdone = payment.objects.get(userid = request.user)
    paymentdone.paymentdone = True
    paymentdone.save()
    return render(request, 'ByteBusterApp/paymentsuccess.html')


@login_required
def paymentfailed(request):
    return render(request, 'ByteBusterApp/paymentfailed.html')


def dashboard(request):
    return render(request, 'ByteBusterApp/dashboard.html', )


def load_template(request, template_id):
    template_name = 'ByteBusterApp/' + template_id + '.html'
    html = render_to_string(template_name, request=request)
    return HttpResponse(html)


# @login_required
# def save_zip_to_db(request):
#     if request.method == 'POST':
#         zip_file = request.FILES.get('zip_content')  # Assuming 'zip_content' is the field name
#         user = request.user  # Get the logged-in user
#
#         if zip_file:
#             # Read the file as binary data
#             zip_content = zip_file.read()
#
#             print(len(zip_content))
#
#             # Save zip_content to the database
#             PricingTable.objects.create(user=user, zip_content=zip_content)
#
#             # Return success response
#             return JsonResponse({'success': True})
#
#     return JsonResponse({'success': False})


# @login_required
# def download_zip(request, id):  # Add 'id' parameter here
#     # Get the PricingTable object with the given id
#     pricing_table = PricingTable.objects.get(id=id)
#
#     # Convert the zip content to bytes
#     zip_content = bytes(pricing_table.zip_content)
#
#     # Create a FileResponse with the zip content
#     response = FileResponse(zip_content, as_attachment=True, filename='pricing_table.zip')
#
#     # Set the Content-Type header to 'application/zip'
#     response['Content-Type'] = 'application/zip'
#
#     return response

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

ByteBusterApp/templates/ByteBusterApp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}ByteBusters{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'temp3.css' %}">
    <meta name="csrf-token" content="{{ csrf_token }}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

</head>
<body>
    <main>
        {% block content %}
        {% endblock %}
  </main>
</body>
</html>

ByteBusterApp/templates/ByteBusterApp/dashboard.html
{% extends "base.html" %}
{% load static %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <nav class="navbar">
        <div class="logo">
            <a href="{% url 'ByteBusterApp:homepage' %}">
                <img src="{% static 'images/logo.png' %}" alt="Bytebuster Logo">
            </a>
        </div>

        {% if user.is_authenticated %}
            Welcome - {{ user.username }}!
            <form action="{% url 'logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="login-button" style="text-decoration: none;">Log Out</button>
            </form>
        {% else %}
            <a href="{% url 'login' %}" class="login-button">Log In</a>
        {% endif %}
    </nav>

    <div class="content">
        <h1 class="dashboard-title">Dashboard <span class="free-text">Free User</span></h1>
        <div class="button-container">
            <a href="{% url 'ByteBusterApp:pricingpage' %}" class="login-button btn-block" style="width: 115px; height: 56px;">Upgrade</a>
        </div>
    </div>

  <div class="dash-section">

        <div class="dash-bar">
            <div class="left-section">
                My Widgets
            </div>
            <div class="right-section">
                <a href="{% url 'ByteBusterApp:homepage' %}" class="create-widget-button">Create Widget</a>
            </div>


        </div>

  </div>

{% endblock %}

ByteBusterApp/templates/ByteBusterApp/homepage.html
{% extends "base.html" %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}

    <nav class="navbar">
        <div class="logo">
            <a href="{% url 'ByteBusterApp:homepage' %}">
                <img src="{% static 'images/logo.png' %}" alt="Bytebuster Logo">
            </a>
        </div>

        {% if user.is_authenticated %}
            Welcome - {{ user.username }}!
            {#    <p><a href="{% url 'password_change' %}">Password Change</a></p>#}
            <form action="{% url 'logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="login-button">Log Out</button>
            </form>
{#            <a href="{% url 'login' %}" class="login-button">Log Out</a>#}
        {% else %}
            <a href="{% url 'login' %}" class="login-button">Log In</a>
        {% endif %}
    </nav>

    <div class="content">
      <h1>Pricing Table Widgets</h1>
      <h2>Increase your website conversion</h2>
    </div>

      <div class="new-section">

        <div class="tmp-bar">
            Select A Template
        </div>

        <div class="left-side">
          <!-- Left side iframe -->
        </div>

        <div class="right-side">

          <div class="image-container" id="template1">
              <img src="{% static 'images/img1.png' %}" alt="Image 1" class="image-content">
              <p class="image-name">Template 1</p>
          </div>

          <div class="image-container" id="template2">
              <img src="{% static 'images/img2.png' %}" alt="Image 2" class="image-content">
              <p class="image-name">Template 2</p>
          </div>

          <div class="image-container" id="template3">
              <img src="{% static 'images/img3.png' %}" alt="Image 3" class="image-content">
              <p class="image-name">Template 3</p>
          </div>
        {% if user.is_authenticated %}
           {% if detail.paymentdone %}
               <button class="continue-button">Continue</button>
            {% else %}
                <a href="{% url 'ByteBusterApp:pricingpage' %}" class="continue-button login-button" id="homepage_continue_button">Continue</a>
            {% endif %}
        {% else %}
            <button class="continue-button">Continue</button>
        {% endif %}
        </div>
      </div>
    <script type="text/javascript" src="{% static 'selected.js' %}"></script>

{% endblock %}

ByteBusterApp/templates/ByteBusterApp/paymentfailed.html
{% extends "base.html" %}
{% load static %}

{% block title %}Payment Failed{% endblock %}

{% block content %}
    <div class="bg-image2"></div>
        <div class="login-container center-screen">
            <div class="center-content">
                <img src="{% static 'images/error.png' %}" alt="Payment Failed Icon" class="icon-image">
                <h2 class="successtitle" style="margin-top: 24px" >Sorry!</h2>
                <h3 class="sucesssubtitle">Your Payment is Unsuccessful</h3>
                <a href="{% url 'ByteBusterApp:pricingpage' %}" class="login-button btn-block" style="margin-top: 24px" >Retry</a>
            </div>
        </div>

{% endblock %}

ByteBusterApp/templates/ByteBusterApp/paymentsuccess.html
{% extends "base.html" %}
{% load static %}

{% block title %}Payment Successful{% endblock %}

{% block content %}
    <div class="bg-image2"></div>
        <div class="login-container center-screen">
            <div class="center-content">
                <img src="{% static 'images/success.png' %}" alt="Payment Success Icon" class="icon-image">
                <h2 class="successtitle" style="margin-top: 24px" >Thank you!</h2>
                <h3 class="sucesssubtitle">Your Payment is Successful</h3>
                <a href="{% url 'ByteBusterApp:homepage' %}" class="login-button btn-block" style="margin-top: 24px" >Go to Dashboard</a>
            </div>
        </div>

{% endblock %}

ByteBusterApp/templates/ByteBusterApp/pricingpage.html
{% extends "base.html" %}
{% load static %}

{% block title %}Pricing{% endblock %}

{% block content %}
    <nav class="navbar">
        <div class="logo">
            <a href="{% url 'ByteBusterApp:homepage' %}">
                <img src="{% static 'images/logo.png' %}" alt="Bytebuster Logo">
            </a>
        </div>

        {% if user.is_authenticated %}
            Welcome - {{ user.username }}!
            {#    <p><a href="{% url 'password_change' %}">Password Change</a></p>#}
            <form action="{% url 'logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="login-button" style="text-decoration: none;">Log Out</button>
            </form>
{#            <a href="{% url 'login' %}" class="login-button">Log Out</a>#}
        {% else %}
            <a href="{% url 'login' %}" class="login-button">Log In</a>
        {% endif %}
    </nav>

    <div class="content">
        <h1>Choose Your Plan</h1>
        <h2>Start using Pricing Table for just $5 and decide which plan is right for you later</h2>
    </div>

  <div class="pricing-section" style="margin-top: 40px">
    <div class="pricing-table">

      <div class="plan">
        <h2>Basic</h2>
        <div class="price">$5/month</div>
        <ul class="features">
            <li><b>1 Widget</b></li>
            <li>Only Bug Fixes</li>
            <li><del>Free Installation Service</del></li>
            <li>100% Ad Free</li>
        </ul>
        {{ paypal_payment.render }}
      </div>

      <div class="plan">
          <h2>Standard</h2>
          <div class="price">$10/month</div>
          <ul class="features">
              <li><b>3 Widgets</b></li>
              <li>Basic Support</li>
              <li>Free Installation Service</li>
              <li>100% Ad Free</li>
          </ul>
          {{ paypal_payment.render }}
      </div>

      <div class="plan">
          <h2>Pro</h2>
          <div class="price">$20/month</div>
          <ul class="features">
              <li><b>9 Widgets</b></li>
              <li>Priority Support</li>
              <li>Free Installation Service</li>
              <li>100% Ad Free</li>
          </ul>
         {{ paypal_payment.render }}
      </div>

  </div>
  </div>

{% endblock %}

ByteBusterApp/templates/ByteBusterApp/template1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Template 1{% endblock %}</title>
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
     <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

{% block content %}
    <div class="container">
      <h5 class="text-center pricing-table-subtitle"></h5>
      <h1 class="text-center pricing-table-title">Pricing Table</h1>
      <div class="row">
        <div class="col-md-4">
          <div class="card pricing-card pricing-plan-basic">
            <div class="card-body">
              <i class="mdi mdi-cube-outline pricing-plan-icon"></i>
              <p class="pricing-plan-title">Basic</p>
              <h3 class="pricing-plan-cost ml-auto">FREE</h3>
              <ul class="pricing-plan-features">
                <li>Unlimited conferences</li>
                <li>100 participants max</li>
                <li>Custom Hold Music</li>
                <li>10 participants max</li>
              </ul>
              <a href="#!" class="btn pricing-plan-purchase-btn">Free</a>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card pricing-card pricing-card-highlighted  pricing-plan-pro">
            <div class="card-body">
                <i class="mdi mdi-trophy pricing-plan-icon"></i>
              <p class="pricing-plan-title">Pro</p>
              <h3 class="pricing-plan-cost ml-auto">$49</h3>
              <ul class="pricing-plan-features">
                <li>Unlimited conferences</li>
                <li>100 participants max</li>
                <li>Custom Hold Music</li>
                <li>10 participants max</li>
              </ul>
              <a href="#!" class="btn pricing-plan-purchase-btn">Purchase</a>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card pricing-card pricing-plan-enterprise">
            <div class="card-body">
              <i class="mdi mdi-wallet-giftcard pricing-plan-icon"></i>
              <p class="pricing-plan-title">Enterprise</p>
              <h3 class="pricing-plan-cost ml-auto">$69</h3>
              <ul class="pricing-plan-features">
                <li>Unlimited conferences</li>
                <li>100 participants max</li>
                <li>Custom Hold Music</li>
                <li>10 participants max</li>
              </ul>
              <a href="#!" class="btn pricing-plan-purchase-btn">Purchase</a>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

ByteBusterApp/templates/ByteBusterApp/template1editor.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="csrf-token" content="{{ csrf_token }}">
    <title>{% block title %}Template 1{% endblock %}</title>
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap" rel="stylesheet">
{#  <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">#}
{#  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">#}
 <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.7.1/jszip.min.js"></script>


</head>

{% block content %}
    <nav class="navbar">
        <div class="logo">
            <a href="{% url 'ByteBusterApp:homepage' %}">
                <img src="{% static 'images/logo.png' %}" alt="Bytebuster Logo">
            </a>
        </div>

        {% if user.is_authenticated %}
            Welcome - {{ user.username }}!
            {#    <p><a href="{% url 'password_change' %}">Password Change</a></p>#}
            <form action="{% url 'logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="login-button">Log Out</button>
            </form>
{#            <a href="{% url 'login' %}" class="login-button">Log Out</a>#}
        {% else %}
            <a href="{% url 'login' %}" class="login-button">Log In</a>
        {% endif %}
    </nav>
    <div class="container" style="max-width: 1900px;">
        <div class="flex-container ">
            <div class="form-container scrollable">
                <label for="table-slider">Number of Tables:</label><br>
                <input type="range" id="table-slider" name="table-slider" min="1" max="3" value="3">
                <form id="basic-form" style="width: 80%">
                    <h4>First Table</h4>
                    <label for="basic-title">Title:</label><br>
                    <input type="text" id="basic-title" name="basic-title" required><br>
                    <label for="basic-cost">Cost:</label><br>
                    <input type="text" id="basic-cost" name="basic-cost" required><br>
                    <label for="basic-feature1">Feature 1:</label><br>
                    <input type="text" id="basic-feature1" name="basic-feature1" required><br>
                    <label for="basic-feature2">Feature 2:</label><br>
                    <input type="text" id="basic-feature2" name="basic-feature2" required><br>
                    <label for="basic-feature3">Feature 3:</label><br>
                    <input type="text" id="basic-feature3" name="basic-feature3" required><br>
                    <label for="basic-feature4">Feature 4:</label><br>
                    <input type="text" id="basic-feature4" name="basic-feature4" required><br>
                    <label for="pricing-plan-purchase-btn">Button Text:</label><br>
                    <input type="text" id="pricing-plan-purchase-btn" name="pricing-plan-purchase-btn" required><br>

                    <input type="submit" value="Update" class="login-button" style="margin-left: 170px;">
                </form>

                <!-- Form for the "Pro" template -->
                <form id="pro-form" style="width: 80%">
                    <h4>Second Table</h4>
                    <label for="pro-title">Title:</label><br>
                    <input type="text" id="pro-title" name="pro-title" required><br>
                    <label for="pro-cost">Cost:</label><br>
                    <input type="text" id="pro-cost" name="pro-cost" required><br>
                    <label for="pro-feature1">Feature 1:</label><br>
                    <input type="text" id="pro-feature1" name="pro-feature1" required><br>
                    <label for="pro-feature2">Feature 2:</label><br>
                    <input type="text" id="pro-feature2" name="pro-feature2" required><br>
                    <label for="pro-feature3">Feature 3:</label><br>
                    <input type="text" id="pro-feature3" name="pro-feature3" required><br>
                    <label for="pro-feature4">Feature 4:</label><br>
                    <input type="text" id="pro-feature4" name="pro-feature4" required><br>
                    <label for="pro-button-text">Button Text:</label><br>
                    <input type="text" id="pro-button-text" name="pro-button-text" required><br>

                    <input type="submit" value="Update" class="login-button" style="margin-left: 170px;">
                </form>

                <!-- Form for the "Enterprise" template -->
                <form id="enterprise-form" style="width: 80%">
                    <h4>Third Table</h4>
                    <label for="enterprise-title">Title:</label><br>
                    <input type="text" id="enterprise-title" name="enterprise-title" required><br>
                    <label for="enterprise-cost">Cost:</label><br>
                    <input type="text" id="enterprise-cost" name="enterprise-cost" required><br>
                    <label for="enterprise-feature1">Feature 1:</label><br>
                    <input type="text" id="enterprise-feature1" name="enterprise-feature1" required><br>
                    <label for="enterprise-feature2">Feature 2:</label><br>
                    <input type="text" id="enterprise-feature2" name="enterprise-feature2" required><br>
                    <label for="enterprise-feature3">Feature 3:</label><br>
                    <input type="text" id="enterprise-feature3" name="enterprise-feature3" required><br>
                    <label for="enterprise-feature4">Feature 4:</label><br>
                    <input type="text" id="enterprise-feature4" name="enterprise-feature4" required><br>
                    <label for="enterprise-button-text">Button Text:</label><br>
                    <input type="text" id="enterprise-button-text" name="enterprise-button-text" required><br>


                    <input type="submit" value="Update" class="login-button" style="margin-left: 170px;">
                </form>
            </div>
            <div class="table-container">
                  <h5 class="text-center pricing-table-subtitle"></h5>
                  <h1 class="text-center pricing-table-title">Pricing Table</h1>
                  <div class="row">
                    <div class="col-md-4">
                      <div class="card pricing-card pricing-plan-basic">
                        <div class="card-body">
                          <i class="mdi mdi-cube-outline pricing-plan-icon"></i>
                          <p class="pricing-plan-title">Basic</p>
                          <h3 class="pricing-plan-cost ml-auto">FREE</h3>
                          <ul class="pricing-plan-features">
                            <li>Unlimited conferences</li>
                            <li>100 participants max</li>
                            <li>Custom Hold Music</li>
                            <li>10 participants max</li>
                          </ul>
                          <a href="#!" class="btn pricing-plan-purchase-btn">Free</a>
                        </div>
                      </div>
                    </div>
                    <div class="col-md-4">
                      <div class="card pricing-card pricing-card-highlighted  pricing-plan-pro">
                        <div class="card-body">
                            <i class="mdi mdi-trophy pricing-plan-icon"></i>
                          <p class="pricing-plan-title">Pro</p>
                          <h3 class="pricing-plan-cost ml-auto">$49</h3>
                          <ul class="pricing-plan-features">
                            <li>Unlimited conferences</li>
                            <li>100 participants max</li>
                            <li>Custom Hold Music</li>
                            <li>10 participants max</li>
                          </ul>
                          <a href="#!" class="btn pricing-plan-purchase-btn">Purchase</a>
                        </div>
                      </div>
                    </div>
                    <div class="col-md-4">
                      <div class="card pricing-card pricing-plan-enterprise">
                        <div class="card-body">
                          <i class="mdi mdi-wallet-giftcard pricing-plan-icon"></i>
                          <p class="pricing-plan-title">Enterprise</p>
                          <h3 class="pricing-plan-cost ml-auto">$69</h3>
                          <ul class="pricing-plan-features">
                            <li>Unlimited conferences</li>
                            <li>100 participants max</li>
                            <li>Custom Hold Music</li>
                            <li>10 participants max</li>
                          </ul>
                          <a href="#!" class="btn pricing-plan-purchase-btn">Purchase</a>
                        </div>
                      </div>
                    </div>
                  </div>
            </div>
        </div>
        {% if user.is_authenticated %}
            <a href="{% url 'ByteBusterApp:template1editor' %}" class="login-button get-code" id="get-code">Get Code</a>
        {% endif %}

    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.5/FileSaver.min.js"></script>
    <script type="text/javascript" src="{% static 'editor.js' %}"></script>
    <script type="text/javascript" src="{% static 'generateCode.js' %}"></script>

{% endblock %}

ByteBusterApp/templates/ByteBusterApp/template_editor.html
<!-- template_editor/templates/template_editor.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Template Editor</title>
</head>
<body>
    <h1>Edit Template</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>

    {% if embedded_code %}
        <h3>Embedded Code:</h3>
        <pre>{{ embedded_code }}</pre>
    {% endif %}
</body>
</html>
s

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}ByteBusters{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>
<body>
    <main>
        {% block content %}
        {% endblock %}
  </main>
</body>
</html>